### ISSUE TITLE
cli-clock: 10#N: value too great for base

### ISSUE THREAD

**Issue by cameronoxley** [tablespoon/fun#4]
Received the following error:

cli-clock: line 234: 1000000000 - 10#N: value too great for base (error token is "10#N")

**Comment by zhangmhao** [comment]
I have come across the same problem too
run environment: os x
```
./cli-clock: line 201: 1000000000 - 10#N: value too great for base (error token is "10#N")

```

**Comment by tablespoon** [comment]
Interesting. Are you also running OSX, cameronoxley? Which version of bash are you guys using?

**Comment by tablespoon** [comment]
I added a fix that I think ought to work for you guys.

**Comment by cameronoxley** [comment]
Running GNU bash, version 3.2.57(1)-release for OSX.

The fix mentioned above did seem to work. Thanks!

**Comment by tablespoon** [comment]
Without having looked at bash's release notes, I'm betting this is a bash 3 limitation. I run CentOS 6 on my iMac at the office, and Fedora on a laptop, both of which include bash 4.

Glad to hear the code change solves the problem for you guys
